# Generated by Django 6.0.3 on 2026-04-16 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('return_requested', 'Return Requested'), ('return_approved', 'Return Approved'), ('welcome_user', 'New User Welcome'), ('promotion_blast', 'Promotional Blast')], max_length=30, unique=True)),
                ('email_subject', models.CharField(blank=True, max_length=300)),
                ('email_body', models.TextField(blank=True, help_text='HTML email body. Use {{order_id}}, {{customer_name}}, {{total}}, {{status}} as placeholders.')),
                ('sms_body', models.CharField(blank=True, help_text='SMS text. Use {{order_id}}, {{customer_name}} as placeholders.', max_length=500)),
                ('push_title', models.CharField(blank=True, max_length=200)),
                ('push_body', models.CharField(blank=True, max_length=500)),
                ('in_app_title', models.CharField(blank=True, max_length=200)),
                ('in_app_message', models.TextField(blank=True)),
                ('in_app_icon', models.CharField(blank=True, default='fa-bell', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['event'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500)),
                ('p256dh_key', models.CharField(max_length=200)),
                ('auth_key', models.CharField(max_length=200)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Subscription',
                'verbose_name_plural': 'Push Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('order_status', 'Order Status Update'), ('shipping_update', 'Shipping Update'), ('delivery_confirmation', 'Delivery Confirmation'), ('return_update', 'Return Update'), ('promotion', 'Promotion'), ('welcome', 'Welcome'), ('system', 'System Alert')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App')], default='in_app', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL to redirect when notification is clicked', max_length=500)),
                ('icon', models.CharField(blank=True, default='fa-bell', help_text='FontAwesome icon class', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, help_text='Extra data (order_id, tracking_number, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
