# Generated by Django 5.2.15 on 2026-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0011_remove_cart_user_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=999.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Configuration',
                'verbose_name_plural': 'Shipping Configuration',
                'db_table': 'store_shippingconfig',
            },
        ),
    ]
