# Generated by Django 5.2.15 on 2026-07-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingConfig',
        ),
    ]
