# Generated by Django 5.2.15 on 2026-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='testimonials_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='testimonials_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='app_image_1',
            field=models.ImageField(blank=True, help_text='Image inside first phone', null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='app_image_2',
            field=models.ImageField(blank=True, help_text='Image inside second phone', null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='app_section_description',
            field=models.TextField(blank=True, default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='app_section_title',
            field=models.CharField(default='App Is Available For Free In App | Play Store', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='app_store_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='play_store_link',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='AboutTestimonial',
        ),
    ]
