# Generated by Django 6.0.3 on 2026-04-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='sliders/')),
                ('link_url', models.CharField(default='/', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'store_homeslider',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='promotions/')),
                ('link_url', models.CharField(default='/', max_length=500)),
                ('badge_text', models.CharField(blank=True, help_text='e.g. NEW, -20%, HOT', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'store_promotioncard',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
