# Generated by Django 5.2.15 on 2026-07-16 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_homeslider_promotioncard'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Empowering Better Health at Home', max_length=200)),
                ('mission_text', models.TextField(blank=True)),
                ('vision_text', models.TextField(blank=True)),
                ('hero_image_1', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('hero_image_2', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('services_title', models.CharField(default='Quality is our priority', max_length=200)),
                ('services_subtitle', models.CharField(blank=True, max_length=500)),
                ('feature1_tagline', models.CharField(default='Features', max_length=100)),
                ('feature1_title', models.CharField(default='Faster Free Delivery', max_length=200)),
                ('feature1_description', models.TextField(blank=True)),
                ('feature1_bullet1', models.CharField(blank=True, max_length=200)),
                ('feature1_bullet2', models.CharField(blank=True, max_length=200)),
                ('feature1_bullet3', models.CharField(blank=True, max_length=200)),
                ('feature1_image1', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('feature1_image2', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('testimonials_title', models.CharField(default='Trusted by Customers', max_length=200)),
                ('testimonials_subtitle', models.CharField(blank=True, max_length=500)),
                ('feature2_tagline', models.CharField(default='Features', max_length=100)),
                ('feature2_title', models.CharField(default='Focus on Customer Satisfaction', max_length=200)),
                ('feature2_description', models.TextField(blank=True)),
                ('feature2_bullet1', models.CharField(blank=True, max_length=200)),
                ('feature2_bullet2', models.CharField(blank=True, max_length=200)),
                ('feature2_bullet3', models.CharField(blank=True, max_length=200)),
                ('feature2_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('team_title', models.CharField(default='Meet Our Team', max_length=200)),
                ('team_subtitle', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='AboutService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='FontAwesome class, e.g. fas fa-truck', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='cms.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. 120+, 100M, 99%', max_length=50)),
                ('label', models.CharField(help_text='e.g. Years of Experience', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='cms.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='about/')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='cms.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_subtitle', models.CharField(blank=True, help_text='e.g. Date or Role', max_length=100)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('review_text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='cms.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
