# Generated by Django 5.2.15 on 2026-07-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_aboutpage_aboutservice_aboutstat_aboutteammember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='feature2_youtube_link',
            field=models.URLField(blank=True, help_text='YouTube link for the video button'),
        ),
    ]
