# Generated by Django 5.2.15 on 2026-07-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_aboutpage_feature2_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
