# Generated by Django 4.2.28 on 2026-03-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_seller_pending',
            field=models.BooleanField(default=False),
        ),
    ]
