# Generated by Django 4.2.28 on 2026-03-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_return_reason_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=999.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Configuration',
                'verbose_name_plural': 'Shipping Configuration',
            },
        ),
    ]
