# Generated by Django 6.0.3 on 2026-04-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_shipping_charge_alter_order_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeSlider',
        ),
        migrations.DeleteModel(
            name='PromotionCard',
        ),
    ]
