# Generated by Django 6.0.3 on 2026-04-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyTaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('BDT', '৳ BDT – Bangladeshi Taka'), ('USD', '$ USD – US Dollar'), ('EUR', '€ EUR – Euro'), ('GBP', '£ GBP – British Pound'), ('INR', '₹ INR – Indian Rupee')], default='BDT', max_length=5)),
                ('currency_symbol', models.CharField(default='৳', max_length=5)),
                ('currency_position', models.CharField(choices=[('before', 'Before price (৳100)'), ('after', 'After price (100৳)')], default='before', max_length=10)),
                ('tax_enabled', models.BooleanField(default=False)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage (e.g. 15.00 for 15%)', max_digits=5)),
                ('tax_label', models.CharField(default='VAT', help_text='Label shown on invoices/cart (e.g. VAT, GST, Tax)', max_length=50)),
                ('tax_included_in_price', models.BooleanField(default=True, help_text='If True, prices already include tax.')),
            ],
            options={
                'verbose_name': 'Currency & Tax Settings',
                'verbose_name_plural': 'Currency & Tax Settings',
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(choices=[('console', 'Console (Development)'), ('smtp', 'SMTP Server'), ('sendgrid', 'SendGrid API'), ('ses', 'Amazon SES')], default='console', max_length=20)),
                ('from_email', models.EmailField(default='noreply@binco.com', max_length=254)),
                ('from_name', models.CharField(default='Binco Ecommerce', max_length=100)),
                ('smtp_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=200)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('sendgrid_api_key', models.CharField(blank=True, max_length=200)),
                ('send_order_confirmation', models.BooleanField(default=True)),
                ('send_shipping_update', models.BooleanField(default=True)),
                ('send_welcome_email', models.BooleanField(default=True)),
                ('send_promotional_emails', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Binco Ecommerce', max_length=200)),
                ('tagline', models.CharField(blank=True, default="Bangladesh's Trusted Marketplace", max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='config/favicons/')),
                ('support_email', models.EmailField(default='support@binco.com', max_length=254)),
                ('support_phone', models.CharField(default='+880 1700-000000', max_length=30)),
                ('address', models.TextField(blank=True, default='Dhaka, Bangladesh')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('footer_text', models.CharField(blank=True, default='© 2025 Binco Ecommerce. All rights reserved.', max_length=500)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable to show a maintenance page to visitors.')),
                ('meta_description', models.CharField(blank=True, default="Binco is Bangladesh's leading marketplace to buy and sell new and used items.", max_length=300)),
                ('google_analytics_id', models.CharField(blank=True, help_text='e.g. G-XXXXXXXXXX', max_length=50)),
            ],
            options={
                'verbose_name': 'General Settings',
                'verbose_name_plural': 'General Settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_enabled', models.BooleanField(default=True, verbose_name='Cash on Delivery Enabled')),
                ('cod_label', models.CharField(default='Cash on Delivery', max_length=100)),
                ('cod_instructions', models.TextField(blank=True, default='Pay with cash when your order is delivered.')),
                ('bkash_enabled', models.BooleanField(default=False, verbose_name='bKash Enabled')),
                ('bkash_merchant_number', models.CharField(blank=True, max_length=20)),
                ('bkash_api_key', models.CharField(blank=True, max_length=200)),
                ('bkash_api_secret', models.CharField(blank=True, max_length=200)),
                ('bkash_sandbox', models.BooleanField(default=True, help_text='Use sandbox/test mode')),
                ('nagad_enabled', models.BooleanField(default=False, verbose_name='Nagad Enabled')),
                ('nagad_merchant_number', models.CharField(blank=True, max_length=20)),
                ('nagad_api_key', models.CharField(blank=True, max_length=200)),
                ('stripe_enabled', models.BooleanField(default=False, verbose_name='Stripe (Card) Enabled')),
                ('stripe_publishable_key', models.CharField(blank=True, max_length=200)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=200)),
                ('stripe_webhook_secret', models.CharField(blank=True, max_length=200)),
                ('stripe_sandbox', models.BooleanField(default=True, help_text='Use test mode keys')),
                ('sslcommerz_enabled', models.BooleanField(default=False, verbose_name='SSLCommerz Enabled')),
                ('sslcommerz_store_id', models.CharField(blank=True, max_length=200)),
                ('sslcommerz_store_passwd', models.CharField(blank=True, max_length=200)),
                ('sslcommerz_sandbox', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway Settings',
                'verbose_name_plural': 'Payment Gateway Settings',
            },
        ),
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('disabled', 'Disabled'), ('twilio', 'Twilio'), ('bulksmsbd', 'BulkSMS BD'), ('sslwireless', 'SSL Wireless')], default='disabled', max_length=20)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=200)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=200)),
                ('twilio_from_number', models.CharField(blank=True, max_length=20)),
                ('bulksms_api_key', models.CharField(blank=True, max_length=200)),
                ('bulksms_sender_id', models.CharField(blank=True, max_length=50)),
                ('send_order_sms', models.BooleanField(default=True)),
                ('send_shipping_sms', models.BooleanField(default=True)),
                ('send_otp_sms', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SMS Configuration',
                'verbose_name_plural': 'SMS Configuration',
            },
        ),
    ]
