# Generated by Django 5.2.15 on 2026-07-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='show_developer_mansib',
            field=models.BooleanField(default=True, help_text='Show "Mansib" in footer credits'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='show_developer_stradigtech',
            field=models.BooleanField(default=True, help_text='Show "StradigTech" in footer credits'),
        ),
    ]
