# Generated by Django 5.2.15 on 2026-07-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_generalsettings_show_developer_mansib_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteStyleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_style', models.CharField(choices=[('header_1', 'Style One — Default'), ('header_2', 'Style Two — Mega menu'), ('header_3', 'Style Three — Minimal')], default='header_1', max_length=20)),
                ('hero_style', models.CharField(choices=[('hero_1', 'Style One — Default Slider'), ('hero_2', 'Style Two — Slider + side panel'), ('hero_3', 'Style Three — Grid slider')], default='hero_1', max_length=20)),
                ('product_card_style', models.CharField(choices=[('card_1', 'Style One — Default'), ('card_2', 'Style Two — Minimal'), ('card_3', 'Style Three — Overlay')], default='card_1', max_length=20)),
                ('footer_style', models.CharField(choices=[('footer_1', 'Style One — Default Dark'), ('footer_2', 'Style Two — Multi-column'), ('footer_3', 'Style Three — Light minimal')], default='footer_1', max_length=20)),
                ('mobile_nav_style', models.CharField(choices=[('mobnav_1', 'Style One — Flat bar'), ('mobnav_2', 'Style Two — Curved floating cart')], default='mobnav_1', max_length=20)),
            ],
            options={
                'verbose_name': 'Website Style Settings',
                'verbose_name_plural': 'Website Style Settings',
            },
        ),
    ]
