# Generated by Django 5.2.15 on 2026-07-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0004_promobannersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='messenger_link',
            field=models.URLField(blank=True, help_text='e.g. https://m.me/yourpage'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='show_messenger_btn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='show_whatsapp_btn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='e.g. +8801700000000', max_length=30),
        ),
    ]
