# Generated by Django 5.2.15 on 2026-07-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_websitestylesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show or hide the promo banner.')),
                ('bg_image', models.ImageField(blank=True, help_text='Background image for the banner. Recommended size: 1920x400.', null=True, upload_to='config/banners/')),
                ('watermark_text', models.CharField(default='EARRING', max_length=50)),
                ('subtitle', models.CharField(default='Upto 35% Discount', max_length=100)),
                ('title', models.CharField(default='Something New In Jewels', max_length=100)),
                ('description', models.CharField(default="22' Carat | 1 Year Warranty | Earrings", max_length=200)),
            ],
            options={
                'verbose_name': 'Promo Banner Settings',
                'verbose_name_plural': 'Promo Banner Settings',
            },
        ),
    ]
